version: '3.4'

configs:
  prometheus_config:
    file: ./prometheus.yml

services:
  urlshortener.api:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    build:
      context: .
      dockerfile: UrlShortener.API/Dockerfile

  urlshortener.service:
    image: ${DOCKER_REGISTRY-}urlshortenerservice
    depends_on:
      - urlshortener.service.db
    build:
      context: .
      dockerfile: UrlShortener.Service/Dockerfile


  urlshortener.statistics:
    image: ${DOCKER_REGISTRY-}urlshortenerstatistics
    build:
      context: .
      dockerfile: UrlShortener.Statistics/Dockerfile

  urlshortener.service.db:
    image: mcr.microsoft.com/mssql/server

  urlshortener.statistics.db:
    image: mcr.microsoft.com/mssql/server

  urlshortener.ui:
    image: ${DOCKER_REGISTRY-}urlshortenerui
    build:
      context: .
      dockerfile: UrlShortener.Ui/Dockerfile

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9095:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - urlshortener.ui
      - urlshortener.api
      - urlshortener.service
      - urlshortener.statistics

