apiVersion: v1
kind: PersistentVolume
metadata:
  name: urlshortener-statistics-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: urlshortener-statistics-db-pv-claim
  hostPath:
    path: "/mnt/data/statistics"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: urlshortener-statistics-db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-statistics-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshortener-statistics-db
  template:
    metadata:
      labels:
        app: urlshortener-statistics-db
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: urlshortener-statistics-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "askfjhajkhbn@°§¦°212SADFAF2"
          volumeMounts:
            - name: urlshortener-statistics-mssqldb
              mountPath: /var/opt/statistics/mssql
      volumes:
        - name: urlshortener-statistics-mssqldb
          persistentVolumeClaim:
            claimName: urlshortener-statistics-db-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: urlshortener-statistics-db
spec:
  type: ClusterIP
  selector:
    app: urlshortener-statistics-db
  ports:
    - name: mssql
      protocol: TCP
      port: 5435
      targetPort: 1433
