# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./UrlShortener.sln
      
    - name: Build
      run: dotnet build --no-restore ./UrlShortener.sln
      
    - name: Test & Cover
      run: dotnet test --no-build --verbosity normal ./UrlShortener.sln --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      
    - name: Copy Coverage to upload location
      run: cp coverage/*/coverage.cobertura.xml coverage/coverage.cobertura.xml
      
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage.cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
